import { Routes } from '@angular/router';

export const routes: Routes = [
    { path: '', redirectTo: 'dashboard', pathMatch: 'full' },
    { path: 'dashboard', loadComponent: () => import('./pages/dashboard/dashboard.component').then(m => m.DashboardComponent) },
    { path: 'users', loadComponent: () => import('./pages/users/users.component').then(m => m.UsersComponent) },
    // { path: 'users/roles', loadComponent: () => import('./pages/users/roles/roles.component').then(m => m.RolesComponent) },
    // { path: 'users/permissions', loadComponent: () => import('./pages/users/permissions/permissions.component').then(m => m.PermissionsComponent) },
    // { path: 'reports/sales', loadComponent: () => import('./pages/reports/sales/sales.component').then(m => m.SalesComponent) },
    { path: 'nodni-form', loadComponent: () => import('./pages/nodni-form/nodni-form.component').then(m => m.NodniFormComponent) },
    { path: 'settings', loadComponent: () => import('./pages/settings/settings.component').then(m => m.SettingsComponent) },
    { path: 'login', loadComponent: () => import('../app/components/login/login.component').then(m => m.LoginComponent) },
    { path: 'customer', loadComponent: () => import('./pages/customer/customer.component').then(m => m.CustomerComponent) },
    { path: 'ferfar-yadi', loadComponent: () => import('./pages/ferfaryadi/ferfaryadi.component').then(m => m.FerfaryadiComponent) },
    { path: 'customer-ferfar', loadComponent: () => import('./pages/ferfaryadi/customer-ferfar/customer-ferfar.component').then(m => m.CustomerFerfarComponent) },
    { path: 'tax-generation', loadComponent: () => import('./pages/tax-generration/tax-generration.component').then(m => m.TaxGenerrationComponent) },
    { path: 'customer-vasuli', loadComponent: () => import('./pages/customer-vasuli/customer-vasuli.component').then(m => m.CustomerVasuliComponent) },
    { path: 'vasuli', loadComponent: () => import('./pages/customer-vasuli/vasuli/vasuli.component').then(m => m.VasuliComponent) },
    { path: 'aadhar-card-show', loadComponent: () => import('./pages/ahval/adhar-card-show/adhar-card-show.component').then(m => m.AdharCardShowComponent) },
    { path: 'mobile-number', loadComponent: () => import('./pages/ahval/mobile-number/mobile-number.component').then(m => m.MobileNumberComponent) },
    { path: 'pani-vyavasta-yadi', loadComponent: () => import('./pages/ahval/pani-vyavasta-yadi/pani-vyavasta-yadi.component').then(m => m.PaniVyavastaYadiComponent) },
    { path: 'toilet-yadi', loadComponent: () => import('./pages/ahval/toilet-yadi/toilet-yadi.component').then(m => m.ToiletYadiComponent) },
    { path: 'malmatta-grahak-yadi', loadComponent: () => import('./pages/ahval/malmatta-grahak-yadi/malmatta-grahak-yadi.component').then(m => m.MalmattaGrahakYadiComponent) },
    { path: 'namuna-8-form', loadComponent: () => import('./pages/ahval/namuna8form/namuna8form.component').then(m => m.Namuna8formComponent) },
    { path: 'namuna-8-form-new', loadComponent: () => import('./pages/ahval/namuna8formNew/namuna-8-form-new.component').then(m => m.Namuna8FormNewComponent) },
    { path: 'namuna-9-form', loadComponent: () => import('./pages/ahval/namuna9form/namuna9form.component').then(m => m.Namuna9formComponent) },
    { path: 'namuna-9-form-new', loadComponent: () => import('./pages/ahval/namuna9form-new/namuna9form-new.component').then(m => m.Namuna9formNewComponent) },
    { path: 'magniche-bill', loadComponent: () => import('./pages/ahval/magniche-bill/magniche-bill.component').then(m => m.MagnicheBillComponent) },
    { path: 'magniche-bill-ward', loadComponent: () => import('./pages/ahval/magniche-bill-ward/magniche-bill-ward.component').then(m => m.MagnicheBillWardComponent) },
    { path: 'imla-kar-form', loadComponent: () => import('./pages/ahval/imla-kar-form/imla-kar-form.component').then(m => m.ImlaKarFormComponent) },
    { path: 'imla-kar-form-new', loadComponent: () => import('./pages/ahval/imla-kar-form-new/imla-kar-form-new.component').then(m => m.ImlaKarFormNewComponent) },
    { path: 'birth-certificate', loadComponent: () => import('./pages/certificates/birth-certificate/birth-certificate.component').then(m => m.BirthCertificateComponent) },
    { path: 'certificate-of-deserted', loadComponent: () => import('./pages/certificates/certificate-of-deserted/certificate-of-deserted.component').then(m => m.CertificateOfDesertedComponent) },
    { path: 'certificate-of-niradhar', loadComponent: () => import('./pages/certificates/certificate-of-niradhar/certificate-of-niradhar.component').then(m => m.CertificateOfNiradharComponent) },
    { path: 'living-certificate', loadComponent: () => import('./pages/certificates/living-certificate/living-certificate.component').then(m => m.LivingCertificateComponent) },
    { path: 'residence-certificate', loadComponent: () => import('./pages/certificates/residence-certificate/residence-certificate.component').then(m => m.ResidenceCertificateComponent) },
    { path: 'no-dues-certificate', loadComponent: () => import('./pages/certificates/no-dues-certificate/no-dues-certificate.component').then(m => m.NoDuesCertificateComponent) },
    { path: 'nucler-family-certificate', loadComponent: () => import('./pages/certificates/nucler-family-certificate/nucler-family-certificate.component').then(m => m.NuclerFamilyCertificateComponent) },
    { path: 'death-certificate', loadComponent: () => import('./pages/certificates/death-certificate/death-certificate.component').then(m => m.DeathCertificateComponent) },
    { path: 'marriage-certificate', loadComponent: () => import('./pages/certificates/marriage-certificate/marriage-certificate.component').then(m => m.MarriageCertificateComponent) },
    { path: 'receipt-of-certificate', loadComponent: () => import('./pages/certificates/receipt-of-certificate/receipt-of-certificate.component').then(m => m.ReceiptOfCertificateComponent) },
    { path: 'widow-certificate', loadComponent: () => import('./pages/certificates/widow-certificate/widow-certificate.component').then(m => m.WidowCertificateComponent) },
    { path: 'toilet-certificate', loadComponent: () => import('./pages/certificates/toilet-certificate/toilet-certificate.component').then(m => m.ToiletCertificateComponent) },
    { path: 'below-poverty-certificate', loadComponent: () => import('./pages/certificates/below-poverty-certificate/below-poverty-certificate.component').then(m => m.BelowPovertyCertificateComponent) },

    { path: 'table-with-pdf', loadComponent: () => import('./pages/table-with-pdf/table-with-pdf.component').then(m => m.TableWithPdfComponent) },
    {path: 'namuna-8-1', loadComponent: () => import('./pages/customer/namuna-8-1/namuna-8-1.component').then(m => m.Namuna81Component)},
    {path: 'namuna-9-1', loadComponent: () => import('./pages/customer/namuna-9-1/namuna-9-1.component').then(m => m.Namuna91Component)},
    {path: 'namuna-8-sarkari', loadComponent: () => import('./pages/customer/namuna-8-sarkari/namuna-8-sarkari.component').then(m => m.Namuna8SarkariComponent)},
    {path: 'namuna-8-new-version-customer-page', loadComponent: () => import('./pages/customer/namuna-8-new-version-customer-page/namuna-8-new-version-customer-page.component').then(m => m.Namuna8NewVersionCustomerPageComponent)},   
    

    {path: 'ward-wise-adhar-list', loadComponent: () => import('./pages/ahval/adhar-card-show/ward-wise-adhar-card-list/ward-wise-adhar-card-list.component').then(m => m.WardWiseAdharCardListComponent)},
    {path: 'ward-wise-mobile-no-list', loadComponent: () => import('./pages/ahval/mobile-number/ward-wise-mobile-no-list/ward-wise-mobile-no-list.component').then(m => m.WardWiseMobileNoListComponent)},
    {path: 'ward-wise-pinyache-pani-list', loadComponent: () => import('./pages/ahval/pani-vyavasta-yadi/ward-wise-pinyache-pani-list/ward-wise-pinyache-pani-list.component').then(m => m.WardWisePinyachePaniListComponent)},
    {path: 'ward-wise-toilet-list', loadComponent: () => import('./pages/ahval/toilet-yadi/ward-wise-toilet-list/ward-wise-toilet-list.component').then(m => m.WardWiseToiletListComponent)},

    {path: 'malmatta-darkahchi-yadi-list', loadComponent: () => import('./pages/ahval/malmatta-grahak-yadi/malmatta-dharkachi-yadi/malmatta-dharkachi-yadi.component').then(m => m.MalmattaDharkachiYadiComponent)},
    {path: 'namuna-10-kar-vasuli', loadComponent: () => import('./pages/customer-vasuli/namuna-10-vasuli/namuna-10-vasuli.component').then(m => m.Namuna10VasuliComponent)},
    {path: 'add-download-pdf-ferfar', loadComponent: () => import('./pages/ferfaryadi/addview-pdf/addview-pdf.component').then(m => m.AddviewPdfComponent)},

    {path: 'malmatta-khula-bhukhand-yadi-list', loadComponent: () => import('./pages/ahval/malmatta-grahak-yadi/malmatta-grahak-yadi-khula-bhukhand/malmatta-grahak-yadi-khula-bhukhand.component').then(m => m.MalmattaGrahakYadiKhulaBhukhandComponent)},
    {path: 'ghar-kar-lavaych-ahe-list', loadComponent: () => import('./pages/ahval/malmatta-grahak-yadi/malmatta-grahak-yadi-ghar-kar/malmatta-grahak-yadi-ghar-kar.component').then(m => m.MalmattaGrahakYadiGharKarComponent)},

    {path: 'namuna-8-anukramika-list', loadComponent: () => import('./pages/ahval/namuna8formNew/anukramika/anukramika.component').then(m => m.AnukramikaComponent) },
    {path: 'namuna-8-ward-new-list', loadComponent: () => import('./pages/ahval/namuna8formNew/namuna8ward-new/namuna8ward-new.component').then(m => m.Namuna8wardNewComponent) },
    {path:'get-namuna-8-1-single-vard-list', loadComponent: () => import('./pages/ahval/namuna8formNew/namuna81-single-ward/namuna81-single-ward.component').then(m => m.Namuna81SingleWardComponent) },
    {path:'get-namuna-8-images', loadComponent: () => import('./pages/ahval/namuna8formNew/namuna-8-images/namuna-8-images.component').then(m => m.Namuna8ImagesComponent) },
    {path:'get-namuna-8-ghosvara', loadComponent: () => import('./pages/ahval/namuna8formNew/namuna-8-ghosvara/namuna-8-ghosvara.component').then(m => m.Namuna8GhosvaraComponent) },
    {path:'get-namuna-8-sarkari-ward', loadComponent: () => import('./pages/ahval/namuna8formNew/namuna-8-sarkari-ward/namuna-8-sarkari-ward.component').then(m => m.Namuna8SarkariWardComponent) },

    {path: 'imla-kar-list', loadComponent: () => import('./pages/ahval/imla-kar-form-new/imlakar-report/imlakar-report.component').then(m => m.ImlakarReportComponent) },
    {path: 'imla-kar-anukramnika-list', loadComponent: () => import('./pages/ahval/imla-kar-form-new/imlakar-anukramanika/imlakar-anukramanika.component').then(m => m.ImlakarAnukramanikaComponent) },

    {path: 'magniche-bill-ward-report-129-1', loadComponent: () => import('./pages/ahval/magniche-bill-ward/report-129-1/report-129-1.component').then(m => m.Report1291Component) },
    {path: 'bill-pay/:token', loadComponent: () => import('./pages/bill-pay/bill-pay.component').then(m => m.BillPayComponent) },
    {path: 'bill-payments', loadComponent: () => import('./pages/bill-payments/bill-payments.component').then(m => m.BillPaymentsComponent) },
    {path: 'public-report/namuna-8-1/:token', loadComponent: () => import('./pages/customer/namuna-8-1/namuna-8-1.component').then(m => m.Namuna81Component) },
    {path: 'magniche-bill-ward-report-129-2', loadComponent: () => import('./pages/ahval/magniche-bill-ward/report-129-2/report-129-2.component').then(m => m.Report1292Component) },

    {path: 'namuna-9-anukramika-list', loadComponent: () => import('./pages/ahval/namuna9form-new/namuna9-anukramnika/namuna9-anukramnika.component').then(m => m.Namuna9AnukramnikaComponent) },
    {path: 'namuna-9-ward-new-list', loadComponent: () => import('./pages/ahval/namuna9form-new/namuna9/namuna9.component').then(m => m.Namuna9Component) },
    {path: 'get-namuna-9-new', loadComponent: () => import('./pages/ahval/namuna9form-new/namuna9-new/namuna9-new.component').then(m => m.Namuna9NewComponent) },
    {path: 'get-namuna-9-ghosvara', loadComponent: () => import('./pages/ahval/namuna9form-new/namuna9-ghosvara/namuna9-ghosvara.component').then(m => m.Namuna9GhosvaraComponent) },

    // chalu-khatedar
    {path: 'chalu-khatedar', loadComponent: () => import('./pages/dashboard/chalu-khatedar/chalu-khatedar.component').then(m => m.ChaluKhatedarComponent) },
    {path: 'adhikrut', loadComponent: () => import('./pages/dashboard/adhikrut/adhikrut.component').then(m => m.AdhikrutComponent) },
    {path: 'indira-awas', loadComponent: () => import('./pages/dashboard/indira-awas/indira-awas.component').then(m => m.IndiraAwasComponent) },
    {path: 'imla-kar', loadComponent: () => import('./pages/dashboard/imla-kar/imla-kar.component').then(m => m.ImlaKarComponent) },
    {path: 'ghar-kar', loadComponent: () => import('./pages/dashboard/ghar-kar/ghar-kar.component').then(m => m.GharKarComponent) },
    {path: 'odogyik', loadComponent: () => import('./pages/dashboard/audogyik/audogyik.component').then(m => m.audogyikComponent) },
    {path: 'manora', loadComponent: () => import('./pages/dashboard/manora/manora.component').then(m => m.manorakComponent) },



];