import { Routes } from '@angular/router';

export const routes: Routes = [
    { path: '', redirectTo: 'dashboard', pathMatch: 'full' },
    { path: 'dashboard', loadComponent: () => import('./pages/dashboard/dashboard.component').then(m => m.DashboardComponent) },
    { path: 'users', loadComponent: () => import('./pages/users/users.component').then(m => m.UsersComponent) },
    // { path: 'users/roles', loadComponent: () => import('./pages/users/roles/roles.component').then(m => m.RolesComponent) },
    // { path: 'users/permissions', loadComponent: () => import('./pages/users/permissions/permissions.component').then(m => m.PermissionsComponent) },
    // { path: 'reports/sales', loadComponent: () => import('./pages/reports/sales/sales.component').then(m => m.SalesComponent) },
    { path: 'nodni-form', loadComponent: () => import('./pages/nodni-form/nodni-form.component').then(m => m.NodniFormComponent) },
    { path: 'settings', loadComponent: () => import('./pages/settings/settings.component').then(m => m.SettingsComponent) },
    { path: 'login', loadComponent: () => import('../app/components/login/login.component').then(m => m.LoginComponent) },
    { path: 'customer', loadComponent: () => import('./pages/customer/customer.component').then(m => m.CustomerComponent) },
    { path: 'ferfar-yadi', loadComponent: () => import('./pages/ferfaryadi/ferfaryadi.component').then(m => m.FerfaryadiComponent) },
    { path: 'customer-ferfar', loadComponent: () => import('./pages/ferfaryadi/customer-ferfar/customer-ferfar.component').then(m => m.CustomerFerfarComponent) },
    { path: 'tax-generation', loadComponent: () => import('./pages/tax-generration/tax-generration.component').then(m => m.TaxGenerrationComponent) },
    { path: 'customer-vasuli', loadComponent: () => import('./pages/customer-vasuli/customer-vasuli.component').then(m => m.CustomerVasuliComponent) },
    { path: 'vasuli', loadComponent: () => import('./pages/customer-vasuli/vasuli/vasuli.component').then(m => m.VasuliComponent) },
    { path: 'aadhar-card-show', loadComponent: () => import('./pages/ahval/adhar-card-show/adhar-card-show.component').then(m => m.AdharCardShowComponent) },
    { path: 'mobile-number', loadComponent: () => import('./pages/ahval/mobile-number/mobile-number.component').then(m => m.MobileNumberComponent) },
    { path: 'pani-vyavasta-yadi', loadComponent: () => import('./pages/ahval/pani-vyavasta-yadi/pani-vyavasta-yadi.component').then(m => m.PaniVyavastaYadiComponent) },
    { path: 'toilet-yadi', loadComponent: () => import('./pages/ahval/toilet-yadi/toilet-yadi.component').then(m => m.ToiletYadiComponent) },
    { path: 'malmatta-grahak-yadi', loadComponent: () => import('./pages/ahval/malmatta-grahak-yadi/malmatta-grahak-yadi.component').then(m => m.MalmattaGrahakYadiComponent) },
    { path: 'namuna-8-form', loadComponent: () => import('./pages/ahval/namuna8form/namuna8form.component').then(m => m.Namuna8formComponent) },
    { path: 'namuna-9-form', loadComponent: () => import('./pages/ahval/namuna9form/namuna9form.component').then(m => m.Namuna9formComponent) },
    { path: 'magniche-bill', loadComponent: () => import('./pages/ahval/magniche-bill/magniche-bill.component').then(m => m.MagnicheBillComponent) },
    { path: 'magniche-bill-ward', loadComponent: () => import('./pages/ahval/magniche-bill-ward/magniche-bill-ward.component').then(m => m.MagnicheBillWardComponent) },
    { path: 'imla-kar-form', loadComponent: () => import('./pages/ahval/imla-kar-form/imla-kar-form.component').then(m => m.ImlaKarFormComponent) },
    { path: 'imla-kar-form-new', loadComponent: () => import('./pages/ahval/imla-kar-form-new/imla-kar-form-new.component').then(m => m.ImlaKarFormNewComponent) },
    { path: 'birth-certificate', loadComponent: () => import('./pages/certificates/birth-certificate/birth-certificate.component').then(m => m.BirthCertificateComponent) },
    { path: 'certificate-of-deserted', loadComponent: () => import('./pages/certificates/certificate-of-deserted/certificate-of-deserted.component').then(m => m.CertificateOfDesertedComponent) },
    { path: 'certificate-of-niradhar', loadComponent: () => import('./pages/certificates/certificate-of-niradhar/certificate-of-niradhar.component').then(m => m.CertificateOfNiradharComponent) },
    { path: 'living-certificate', loadComponent: () => import('./pages/certificates/living-certificate/living-certificate.component').then(m => m.LivingCertificateComponent) },
    { path: 'residence-certificate', loadComponent: () => import('./pages/certificates/residence-certificate/residence-certificate.component').then(m => m.ResidenceCertificateComponent) },
    { path: 'no-dues-certificate', loadComponent: () => import('./pages/certificates/no-dues-certificate/no-dues-certificate.component').then(m => m.NoDuesCertificateComponent) },
    { path: 'nucler-family-certificate', loadComponent: () => import('./pages/certificates/nucler-family-certificate/nucler-family-certificate.component').then(m => m.NuclerFamilyCertificateComponent) },
    { path: 'death-certificate', loadComponent: () => import('./pages/certificates/death-certificate/death-certificate.component').then(m => m.DeathCertificateComponent) },
    { path: 'marriage-certificate', loadComponent: () => import('./pages/certificates/marriage-certificate/marriage-certificate.component').then(m => m.MarriageCertificateComponent) },
    { path: 'receipt-of-certificate', loadComponent: () => import('./pages/certificates/receipt-of-certificate/receipt-of-certificate.component').then(m => m.ReceiptOfCertificateComponent) },
    { path: 'widow-certificate', loadComponent: () => import('./pages/certificates/widow-certificate/widow-certificate.component').then(m => m.WidowCertificateComponent) },
    { path: 'toilet-certificate', loadComponent: () => import('./pages/certificates/toilet-certificate/toilet-certificate.component').then(m => m.ToiletCertificateComponent) },
    { path: 'below-poverty-certificate', loadComponent: () => import('./pages/certificates/below-poverty-certificate/below-poverty-certificate.component').then(m => m.BelowPovertyCertificateComponent) },

    { path: 'table-with-pdf', loadComponent: () => import('./pages/table-with-pdf/table-with-pdf.component').then(m => m.TableWithPdfComponent) },
    {path: 'namuna-8-1', loadComponent: () => import('./pages/customer/namuna-8-1/namuna-8-1.component').then(m => m.Namuna81Component)},
    {path: 'namuna-9-1', loadComponent: () => import('./pages/customer/namuna-9-1/namuna-9-1.component').then(m => m.Namuna91Component)},
    {path: 'namuna-8-sarkari', loadComponent: () => import('./pages/customer/namuna-8-sarkari/namuna-8-sarkari.component').then(m => m.Namuna8SarkariComponent)},
];